version: "3.9"

services:
  backend:
    image: django-cra-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DEBUG=0
      - DEV_MODE=0
      - PORT=8000

  # Example Postgres (commented out by default)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=app
  #     - POSTGRES_PASSWORD=app
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
